import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { isBuiltin } from 'node:module';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';

// The gateway installs these plugins into OpenCode as single self-contained files.
// Embed their sources so Node and bundled Electron builds share the same installer.
const plugins = [
  { name: 'side-chat', label: 'side-chat', constant: 'SIDE_CHAT_PLUGIN' },
  { name: 'tasks', label: 'tasks', constant: 'TASKS_PLUGIN' },
  { name: 'desktop-tools', label: 'desktop-tools', constant: 'DESKTOP_TOOLS_PLUGIN' },
];
const check = process.argv.includes('--check');
let stale = false;

for (const { name, label, constant } of plugins) {
  const input = new URL(`../packages/${name}-plugin/src/plugin.ts`, import.meta.url);
  const output = new URL(`../packages/gateway/src/${name}-plugin.generated.ts`, import.meta.url);
  const transpiled = ts.transpileModule(readFileSync(input, 'utf8'), {
    compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 },
    reportDiagnostics: true,
  });
  const { diagnostics } = transpiled;
  const outputText =
    name === 'desktop-tools'
      ? execFileSync(
          'bun',
          ['build', fileURLToPath(input), '--target=node', '--format=esm', '--minify'],
          { encoding: 'utf8', maxBuffer: 16 * 1024 * 1024 },
        )
      : transpiled.outputText;
  if (diagnostics?.length) throw new Error(`The ${label} plugin did not transpile.`);
  // Single-file plugins may use Node builtins, but cannot depend on adjacent packages.
  const parsed = ts.createSourceFile('plugin.js', outputText, ts.ScriptTarget.ES2022, true);
  function checkImports(node) {
    if (
      (ts.isImportDeclaration(node) || ts.isExportDeclaration(node)) &&
      node.moduleSpecifier &&
      (!ts.isStringLiteral(node.moduleSpecifier) ||
        !node.moduleSpecifier.text.startsWith('node:') ||
        !isBuiltin(node.moduleSpecifier.text))
    )
      throw new Error(`The ${label} plugin may import only node: builtins at runtime.`);
    if (
      ts.isCallExpression(node) &&
      (node.expression.kind === ts.SyntaxKind.ImportKeyword ||
        (ts.isIdentifier(node.expression) && node.expression.text === 'require'))
    )
      throw new Error(`The ${label} plugin must use static node: imports.`);
    ts.forEachChild(node, checkImports);
  }
  checkImports(parsed);
  const version = createHash('sha256').update(outputText).digest('hex').slice(0, 12);
  const source = `// OpenCodex ${label} plugin ${version}. Installed by OpenCodex; edits are replaced.\n${outputText}`;
  // Keep Electron's import.meta rewrite out of bundled client code embedded as data.
  const embedded =
    name === 'desktop-tools'
      ? `Buffer.from(${JSON.stringify(Buffer.from(source).toString('base64'))}, 'base64').toString('utf8')`
      : JSON.stringify(source);
  const generated = `// Generated by \`bun plugins\` from packages/${name}-plugin/src/plugin.ts. Do not edit.
export const ${constant} = { version: ${JSON.stringify(version)}, source: ${embedded} };
`;
  if (!check) {
    writeFileSync(output, generated);
    console.log(`Embedded ${label} plugin ${version}.`);
  } else if (readFileSync(output, 'utf8') !== generated) {
    console.error(`The embedded ${label} plugin is stale. Run \`bun plugins\`.`);
    stale = true;
  }
}
if (stale) process.exit(1);
if (check) console.log('Embedded plugins are current.');
