import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import ts from 'typescript';

// The gateway installs these plugins into OpenCode as single self-contained files.
// Embed their transpiled sources so browser, Node, and bundled Electron builds share them.
const plugins = [
  { name: 'side-chat', label: 'side-chat', constant: 'SIDE_CHAT_PLUGIN' },
  { name: 'tasks', label: 'tasks', constant: 'TASKS_PLUGIN' },
];
const check = process.argv.includes('--check');
let stale = false;

for (const { name, label, constant } of plugins) {
  const input = new URL(`../packages/${name}-plugin/src/plugin.ts`, import.meta.url);
  const output = new URL(`../packages/gateway/src/${name}-plugin.generated.ts`, import.meta.url);
  const { outputText, diagnostics } = ts.transpileModule(readFileSync(input, 'utf8'), {
    compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 },
    reportDiagnostics: true,
  });
  if (diagnostics?.length) throw new Error(`The ${label} plugin did not transpile.`);
  if (/^\s*import\s(?!type\b)/m.test(outputText) || /\brequire\(/.test(outputText))
    throw new Error(`The ${label} plugin must not have runtime imports.`);
  const version = createHash('sha256').update(outputText).digest('hex').slice(0, 12);
  const source = `// OpenCodex ${label} plugin ${version}. Installed by OpenCodex; edits are replaced.\n${outputText}`;
  const generated = `// Generated by \`bun plugins\` from packages/${name}-plugin/src/plugin.ts. Do not edit.
export const ${constant} = { version: ${JSON.stringify(version)}, source: ${JSON.stringify(source)} };
`;
  if (!check) {
    writeFileSync(output, generated);
    console.log(`Embedded ${label} plugin ${version}.`);
  } else if (readFileSync(output, 'utf8') !== generated) {
    console.error(`The embedded ${label} plugin is stale. Run \`bun plugins\`.`);
    stale = true;
  }
}
if (stale) process.exit(1);
if (check) console.log('Embedded plugins are current.');
